using System;
using ZeoOverlay;

namespace ZeoCore
{
    // Ported from the existing SettingsForm: labels, ranges, steps, choices and actions.
    // The shared OverlaySettings model is compiled into both hosts; it owns persistence.
    internal static partial class ZeoNativeCatalog
    {
        internal static readonly string[] Pages = { "FLIGHT", "SCOPE", "FLEET", "LAYOUT", "THEME", "MARKERS", "PRIVACY", "CAPTURE", "AMMO", "ROSTER", "DISTRESS" };
        internal static readonly NativeOption[] Options = {
            Bool("SCOPE","CAMERA RESPONSE","Fast camera marker updates","FastCameraMarkers",s => s.FastCameraMarkers,(s,v) => s.FastCameraMarkers=v),
            Bool("FLIGHT","FLIGHT DISPLAY","HUD enabled","HudEnabled",s => s.HudEnabled, (s,v) => { s.HudEnabled=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Center flight crosshair","ShowCrosshair",s => s.ShowCrosshair, (s,v) => { s.ShowCrosshair=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","SHIP STATUS panel","ShowFlightData",s => s.ShowFlightData, (s,v) => { s.ShowFlightData=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","TRACKS ON SCOPE panel","ShowTrackPanel",s => s.ShowTrackPanel, (s,v) => { s.ShowTrackPanel=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Optional compact FleetLink strip","ShowLinkPanel",s => s.ShowLinkPanel, (s,v) => { s.ShowLinkPanel=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show H20","ShowShipH2O",s => s.ShowShipH2O, (s,v) => { s.ShowShipH2O=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show O2","ShowShipO2",s => s.ShowShipO2, (s,v) => { s.ShowShipO2=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show Fusion Pellets","ShowShipFusion",s => s.ShowShipFusion, (s,v) => { s.ShowShipFusion=v; }),
            Number("FLIGHT","FLIGHT DISPLAY","Fusion reserve target","FusionReserveTarget",100,1000000,100,0,s => s.FusionReserveTarget, (s,v) => s.FusionReserveTarget=(int)v),
            Bool("FLIGHT","FLIGHT DISPLAY","Show Drive health","ShowShipDrive",s => s.ShowShipDrive, (s,v) => { s.ShowShipDrive=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show Reactor health","ShowShipReactor",s => s.ShowShipReactor, (s,v) => { s.ShowShipReactor=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show Power output","ShowShipPower",s => s.ShowShipPower, (s,v) => { s.ShowShipPower=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show Ship HP","ShowShipHp",s => s.ShowShipHp, (s,v) => { s.ShowShipHp=v; }),
            Bool("FLIGHT","FLIGHT DISPLAY","Show Speed","ShowShipSpeed",s => s.ShowShipSpeed, (s,v) => { s.ShowShipSpeed=v; }),
            Bool("FLIGHT","LABEL DETAIL","Show names when relevant","ShowNames",s => s.ShowNames, (s,v) => { s.ShowNames=v; }),
            Bool("FLIGHT","LABEL DETAIL","Show distance when relevant","ShowDistance",s => s.ShowDistance, (s,v) => { s.ShowDistance=v; }),
            Bool("FLIGHT","LABEL DETAIL","Show closing on priority contacts","ShowClosingOnPriority",s => s.ShowClosingOnPriority, (s,v) => { s.ShowClosingOnPriority=v; }),
            Bool("SCOPE","SCOPE SOURCES","Local Spectrum signals","ShowLocalSpectrum",s => s.ShowLocalSpectrum, (s,v) => { s.ShowLocalSpectrum=v; }),
            Bool("SCOPE","SCOPE SOURCES","Local WeaponCore tracks","ShowLocalWeaponCore",s => s.ShowLocalWeaponCore, (s,v) => { s.ShowLocalWeaponCore=v; }),
            Bool("SCOPE","SCOPE SOURCES","Hostile contacts","ShowHostiles",s => s.ShowHostiles, (s,v) => { s.ShowHostiles=v; }),
            Bool("SCOPE","SCOPE SOURCES","Neutral / unknown contacts","ShowNeutrals",s => s.ShowNeutrals, (s,v) => { s.ShowNeutrals=v; }),
            Bool("SCOPE","OBSERVER MODE","Keep TOS visible outside ship","KeepTosOutsideShip",s => s.KeepTosOutsideShip, (s,v) => { s.KeepTosOutsideShip=v; }),
            Bool("SCOPE","FLIGHT HUD SCOPE","Scope STATUS / speed-vector columns","ScopeShowStatus",s => s.ScopeShowStatus, (s,v) => { s.ScopeShowStatus=v; }),
            Bool("SCOPE","FLIGHT HUD SCOPE","Scope CORE / name column","ScopeShowCore",s => s.ScopeShowCore, (s,v) => { s.ScopeShowCore=v; }),
            Number("SCOPE","FLIGHT HUD SCOPE","Scope capacity (tracks)","ScopeRows",3,16,1,0,s => s.ScopeRows, (s,v) => s.ScopeRows=(int)v),
            Number("SCOPE","FLIGHT HUD SCOPE","Scope text scale","ScopeTextScale",0.60,2.50,0.05,2,s => s.ScopeTextScale, (s,v) => s.ScopeTextScale=v),
            Number("SCOPE","FLIGHT HUD SCOPE","Scope width","ScopeWidthScale",0.75,2.50,0.05,2,s => s.ScopeWidthScale, (s,v) => s.ScopeWidthScale=v),
            Bool("SCOPE","TRACK STABILITY","Smooth / predict track motion between sensor updates","PredictTrackMotion",s => s.PredictTrackMotion, (s,v) => { s.PredictTrackMotion=v; }),
            Number("SCOPE","TRACK STABILITY","Prediction limit seconds","PredictionLimitSeconds",0.10,2.50,0.05,2,s => s.PredictionLimitSeconds, (s,v) => s.PredictionLimitSeconds=v),
            Number("SCOPE","RANGE + DECLUTTER","Max contact markers","MaxContactMarkers",1,40,1,0,s => s.MaxContactMarkers, (s,v) => s.MaxContactMarkers=(int)v),
            Number("SCOPE","RANGE + DECLUTTER","Max range km","MaxRangeKm",5,500,5,0,s => s.MaxRangeKm, (s,v) => s.MaxRangeKm=v),
            Bool("SCOPE","RANGE + DECLUTTER","Declutter overlapping markers","Declutter",s => s.Declutter, (s,v) => { s.Declutter=v; }),
            Number("SCOPE","RANGE + DECLUTTER","Declutter radius","DeclutterRadius",0.005,0.200,0.005,3,s => s.DeclutterRadius, (s,v) => s.DeclutterRadius=v),
            Bool("SCOPE","RANGE + DECLUTTER","Suppress subgrid / wreck clutter","SuppressSubgridClutter",s => s.SuppressSubgridClutter, (s,v) => { s.SuppressSubgridClutter=v; }),
            Number("SCOPE","RANGE + DECLUTTER","Stale after seconds","StaleSeconds",2,60,1,0,s => s.StaleSeconds, (s,v) => s.StaleSeconds=(int)v),
            Number("SCOPE","RANGE + DECLUTTER","Last-known timeout","LastKnownSeconds",5,120,1,0,s => s.LastKnownSeconds, (s,v) => s.LastKnownSeconds=(int)v),
            Bool("SCOPE","PERFORMANCE","Adaptive tactical processing","AdaptiveTacticalRate",s => s.AdaptiveTacticalRate, (s,v) => { s.AdaptiveTacticalRate=v; }),
            Number("SCOPE","PERFORMANCE","Processing cap / source","TacticalProcessingCap",24,192,8,0,s => s.TacticalProcessingCap, (s,v) => s.TacticalProcessingCap=(int)v),
            Bool("FLEET","FLEET / SHARED PICTURE","Receive shared FleetLink picture","ReceiveFleetLink",s => s.ReceiveFleetLink, (s,v) => { s.ReceiveFleetLink=v; }),
            Bool("FLEET","FLEET / SHARED PICTURE","Zeo remote friendlies","ShowFleetFriendlies",s => s.ShowFleetFriendlies, (s,v) => { s.ShowFleetFriendlies=v; }),
            Bool("FLEET","FLEET / SHARED PICTURE","Zeo shared WeaponCore threats","ShowSharedContacts",s => s.ShowSharedContacts, (s,v) => { s.ShowSharedContacts=v; }),
            Bool("FLEET","FLEET / SHARED PICTURE","Zeo shared Spectrum signals","ShowSharedSignals",s => s.ShowSharedSignals, (s,v) => { s.ShowSharedSignals=v; }),
            Bool("FLEET","FLEET / SHARED PICTURE","Friendly world markers","ShowFriendlyMarkers",s => s.ShowFriendlyMarkers, (s,v) => { s.ShowFriendlyMarkers=v; }),
            Number("FLEET","FLEET / SHARED PICTURE","Max friendly markers","MaxFriendlyMarkers",1,24,1,0,s => s.MaxFriendlyMarkers, (s,v) => s.MaxFriendlyMarkers=(int)v),
            Bool("FLEET","FLEET / SHARED PICTURE","Unlimited-distance same-sector friendly markers","RemoteFriendlyNoRangeLimit",s => s.RemoteFriendlyNoRangeLimit, (s,v) => { s.RemoteFriendlyNoRangeLimit=v; }),
            Bool("FLEET","FLEET / SHARED PICTURE","Unlimited-distance shared tactical tracks","SharedTacticalNoRangeLimit",s => s.SharedTacticalNoRangeLimit, (s,v) => { s.SharedTacticalNoRangeLimit=v; }),
            Bool("FLEET","TACTICAL SHARING","Share my WeaponCore threats","ShareWeaponCoreContacts",s => s.ShareWeaponCoreContacts, (s,v) => { s.ShareWeaponCoreContacts=v; }),
            Bool("FLEET","TACTICAL SHARING","Share my Spectrum signals","ShareSpectrumSignals",s => s.ShareSpectrumSignals, (s,v) => { s.ShareSpectrumSignals=v; }),
            Choice("LAYOUT","HUD FRAME STYLE","HUD FRAME","FrameStyle",new[] {"SE INDUSTRIAL","FIGHTER HUD","MARS TACTICAL","BELTER UTILITY","NAVY GLASS","STEALTH","WAR ROOM","COMMAND GRID","REDLINE","BLACKSITE","CHEVRON","SPLIT WING","HEX COMMAND","RAZOR","LEGACY GLASS","KEEN SIGNAL","WEAPON CORE"},s => s.FrameStyle, (s,v) => s.FrameStyle=v),
            Choice("LAYOUT","HUD FRAME STYLE","FONT STYLE","FontStyle",new[] {"MATCH HUD","CONDENSED","TECH","STANDARD"},s => s.FontStyle, (s,v) => s.FontStyle=v),
            Bool("LAYOUT","PANEL BACKINGS","Ship info backing","BackingShipInfo",s => s.BackingShipInfo, (s,v) => { s.BackingShipInfo=v; }),
            Bool("LAYOUT","PANEL BACKINGS","TOS / scope backing","BackingTos",s => s.BackingTos, (s,v) => { s.BackingTos=v; }),
            Bool("LAYOUT","PANEL BACKINGS","Fleet / network backing","BackingFleetLink",s => s.BackingFleetLink, (s,v) => { s.BackingFleetLink=v; }),
            Bool("LAYOUT","PANEL BACKINGS","Ammo backing","BackingAmmo",s => s.BackingAmmo, (s,v) => { s.BackingAmmo=v; }),
            Bool("LAYOUT","PANEL BACKINGS","Fleet roster backing","BackingRoster",s => s.BackingRoster, (s,v) => { s.BackingRoster=v; }),
            Bool("LAYOUT","PANEL BACKINGS","Distress banner backing","BackingDistress",s => s.BackingDistress, (s,v) => { s.BackingDistress=v; }),
            Number("LAYOUT","PANEL SIZE","Global text scale","TextScale",0.65,2.50,0.05,2,s => s.TextScale, (s,v) => s.TextScale=v),
            Number("LAYOUT","PANEL SIZE","Flight panel scale","FlightScale",0.60,2.25,0.05,2,s => s.FlightScale, (s,v) => s.FlightScale=v),
            Number("LAYOUT","PANEL SIZE","Scope backplate scale","ScopePanelScale",0.60,2.25,0.05,2,s => s.ScopePanelScale, (s,v) => s.ScopePanelScale=v),
            Number("LAYOUT","PANEL SIZE","Fleet panel scale","LinkPanelScale",0.60,2.25,0.05,2,s => s.LinkPanelScale, (s,v) => s.LinkPanelScale=v),
            Number("LAYOUT","PANEL SIZE","Ammo panel scale","AmmoPanelScale",0.60,2.25,0.05,2,s => s.AmmoPanelScale, (s,v) => s.AmmoPanelScale=v),
            Number("LAYOUT","PANEL SIZE","Roster panel scale","RosterPanelScale",0.60,2.25,0.05,2,s => s.RosterPanelScale, (s,v) => s.RosterPanelScale=v),
            Number("LAYOUT","PANEL SIZE","Panel backing opacity","PanelOpacity",60,245,5,0,s => s.PanelOpacity, (s,v) => s.PanelOpacity=(int)v),
            Number("LAYOUT","PANEL SIZE","Panel inner padding","PanelPaddingScale",0.60,2.00,0.05,2,s => s.PanelPaddingScale, (s,v) => s.PanelPaddingScale=v),
            Number("LAYOUT","PANEL SIZE","Panel border width","BorderWidth",0.50,4.00,0.05,2,s => s.BorderWidth, (s,v) => s.BorderWidth=v),
            Number("LAYOUT","PANEL POSITION","Flight X","FlightX",-0.98,0.98,0.01,2,s => s.FlightX, (s,v) => s.FlightX=v),
            Number("LAYOUT","PANEL POSITION","Flight Y","FlightY",-0.98,0.98,0.01,2,s => s.FlightY, (s,v) => s.FlightY=v),
            Number("LAYOUT","PANEL POSITION","Scope X","TrackPanelX",-0.98,0.98,0.01,2,s => s.TrackPanelX, (s,v) => s.TrackPanelX=v),
            Number("LAYOUT","PANEL POSITION","Scope Y","TrackPanelY",-0.98,0.98,0.01,2,s => s.TrackPanelY, (s,v) => s.TrackPanelY=v),
            Number("LAYOUT","PANEL POSITION","Fleet X","LinkPanelX",-0.98,0.98,0.01,2,s => s.LinkPanelX, (s,v) => s.LinkPanelX=v),
            Number("LAYOUT","PANEL POSITION","Fleet Y","LinkPanelY",-0.98,0.98,0.01,2,s => s.LinkPanelY, (s,v) => s.LinkPanelY=v),
            Number("LAYOUT","PANEL POSITION","Ammo X","AmmoX",-0.98,0.98,0.01,2,s => s.AmmoX, (s,v) => s.AmmoX=v),
            Number("LAYOUT","PANEL POSITION","Ammo Y","AmmoY",-0.98,0.98,0.01,2,s => s.AmmoY, (s,v) => s.AmmoY=v),
            Number("LAYOUT","PANEL POSITION","Roster X","RosterX",-0.98,0.98,0.01,2,s => s.RosterX, (s,v) => s.RosterX=v),
            Number("LAYOUT","PANEL POSITION","Roster Y","RosterY",-0.98,0.98,0.01,2,s => s.RosterY, (s,v) => s.RosterY=v),
            ResetLayout("LAYOUT","PANEL POSITION","RESET POLISHED LAYOUT"),
            Number("LAYOUT","INTEGRATED HUD // LIVE VISUALS","MAX MARKER SIZE","MaxMarkerScale",0.50,1.00,0.05,2,s => s.MaxMarkerScale,(s,v) => s.MaxMarkerScale=v),
            Bool("LAYOUT","INTEGRATED HUD // LIVE VISUALS","FOLLOW GAME HUD","FollowGameHud",s => s.FollowGameHud, (s,v) => { s.FollowGameHud=v; }),
            Choice("THEME","THEME PRESET","THEME","ThemePreset",new[] {"GRAPHITE","MONOCHROME","AMBER","HIGH CONTRAST","CUSTOM","WAR ROOM","KEEN NATIVE"},s => s.ThemePreset, (s,v) => s.ApplyTheme(v)),
            Color("THEME","HUD COLORS","HUD text","HudTextColor",s => s.HudTextColor, (s,v) => s.HudTextColor=v),
            Color("THEME","HUD COLORS","Secondary text","HudSecondaryColor",s => s.HudSecondaryColor, (s,v) => s.HudSecondaryColor=v),
            Color("THEME","HUD COLORS","Panel backing","HudPanelColor",s => s.HudPanelColor, (s,v) => s.HudPanelColor=v),
            Color("THEME","HUD COLORS","Panel border","HudBorderColor",s => s.HudBorderColor, (s,v) => s.HudBorderColor=v),
            Color("THEME","HUD COLORS","Crosshair","CrosshairColor",s => s.CrosshairColor, (s,v) => s.CrosshairColor=v),
            Color("THEME","HUD COLORS","Spectrum tracks","SpectrumColor",s => s.SpectrumColor, (s,v) => s.SpectrumColor=v),
            Color("THEME","HUD COLORS","Friendly tracks","FriendlyColor",s => s.FriendlyColor, (s,v) => s.FriendlyColor=v),
            Color("THEME","HUD COLORS","Hostile tracks","HostileColor",s => s.HostileColor, (s,v) => s.HostileColor=v),
            Color("THEME","HUD COLORS","Neutral tracks","NeutralColor",s => s.NeutralColor, (s,v) => s.NeutralColor=v),
            Color("THEME","HUD COLORS","Stale tracks","StaleColor",s => s.StaleColor, (s,v) => s.StaleColor=v),
            Color("THEME","HUD COLORS","Focused track","FocusColor",s => s.FocusColor, (s,v) => s.FocusColor=v),
            Color("THEME","HUD COLORS","Distress / SOS","DistressColor",s => s.DistressColor, (s,v) => s.DistressColor=v),
            Color("THEME","MENU COLORS","Menu background","MenuBackgroundColor",s => s.MenuBackgroundColor, (s,v) => s.MenuBackgroundColor=v),
            Color("THEME","MENU COLORS","Menu panel","MenuPanelColor",s => s.MenuPanelColor, (s,v) => s.MenuPanelColor=v),
            Color("THEME","MENU COLORS","Menu text","MenuTextColor",s => s.MenuTextColor, (s,v) => s.MenuTextColor=v),
            Color("THEME","MENU COLORS","Menu accent","MenuAccentColor",s => s.MenuAccentColor, (s,v) => s.MenuAccentColor=v),
            Choice("MARKERS","CONTACT ICONS","MARKER ANCHOR","MarkerAnchor",new[] {"SENSOR POSITION","GRID CENTER","SPECTRUM / AUTO"},s => s.MarkerAnchor, (s,v) => s.MarkerAnchor=v),
            Number("MARKERS","SPECTRUM RETICLE","Spectrum reticle scale","SpectrumMarkerScale",0.50,3.00,0.05,2,s => s.SpectrumMarkerScale, (s,v) => s.SpectrumMarkerScale=v),
            Number("MARKERS","SPECTRUM RETICLE","Spectrum track ID scale","SpectrumIdScale",0.50,3.00,0.05,2,s => s.SpectrumIdScale, (s,v) => s.SpectrumIdScale=v),
            Number("MARKERS","FRIENDLY MARKERS","Friendly icon scale","FriendlyMarkerScale",0.50,3.00,0.05,2,s => s.FriendlyMarkerScale, (s,v) => s.FriendlyMarkerScale=v),
            Number("MARKERS","FRIENDLY MARKERS","Friendly track ID scale","FriendlyIdScale",0.50,3.00,0.05,2,s => s.FriendlyIdScale, (s,v) => s.FriendlyIdScale=v),
            Number("MARKERS","OTHER MARKERS","Hostile / contact scale","HostileMarkerScale",0.50,3.00,0.05,2,s => s.HostileMarkerScale, (s,v) => s.HostileMarkerScale=v),
            Number("MARKERS","OTHER MARKERS","Focused target multiplier","FocusMarkerScale",0.50,3.00,0.05,2,s => s.FocusMarkerScale, (s,v) => s.FocusMarkerScale=v),
            Number("MARKERS","OTHER MARKERS","Off-screen multiplier","OffscreenMarkerScale",0.50,3.00,0.05,2,s => s.OffscreenMarkerScale, (s,v) => s.OffscreenMarkerScale=v),
            Number("MARKERS","OTHER MARKERS","Center crosshair scale","CrosshairScale",0.50,3.00,0.05,2,s => s.CrosshairScale, (s,v) => s.CrosshairScale=v),
            Bool("MARKERS","ALIGNMENT TEST","Show tiny center dot under every world marker","ShowMarkerAnchorDot",s => s.ShowMarkerAnchorDot, (s,v) => { s.ShowMarkerAnchorDot=v; }),
            Bool("PRIVACY","STREAMER PRIVACY","STREAMER MODE","StreamerMode",s => s.CaptureSafeHud && s.CaptureSafeMenu, (s,v) => { s.CaptureSafeHud=v; s.CaptureSafeMenu=v; }),
            Bool("PRIVACY","DATA EXPORT / PRIVACY","Transmit my telemetry to Zeo server","TransmitTelemetry",s => s.TransmitTelemetry, (s,v) => { s.TransmitTelemetry=v; }),
            Bool("PRIVACY","DATA EXPORT / PRIVACY","Write local last-payload.json","WriteLocalPayload",s => s.WriteLocalPayload, (s,v) => { s.WriteLocalPayload=v; }),
            Bool("CAPTURE","STREAMER MODE","STREAMER MODE","StreamerMode",s => s.CaptureSafeHud && s.CaptureSafeMenu, (s,v) => { s.CaptureSafeHud=v; s.CaptureSafeMenu=v; }),
            Bool("CAPTURE","CAPTURE-SAFE RENDERER","Exclude Zeo HUD from supported screen capture","CaptureSafeHud",s => s.CaptureSafeHud, (s,v) => { s.CaptureSafeHud=v; }),
            Bool("CAPTURE","CAPTURE-SAFE RENDERER","Exclude Zeo settings menu from supported capture","CaptureSafeMenu",s => s.CaptureSafeMenu, (s,v) => { s.CaptureSafeMenu=v; }),
            Bool("CAPTURE","CAPTURE-SAFE RENDERER","Auto-launch ZeoOverlay with the plugin","OverlayAutoLaunch",s => s.OverlayAutoLaunch, (s,v) => { s.OverlayAutoLaunch=v; }),
            Bool("AMMO","AMMO TRACKER","Show AMMUNITION panel","ShowAmmoPanel",s => s.ShowAmmoPanel, (s,v) => { s.ShowAmmoPanel=v; }),
            Bool("AMMO","AMMO TRACKER","Only ammo relevant / stocked on this ship","AmmoOnlyRelevant",s => s.AmmoOnlyRelevant, (s,v) => { s.AmmoOnlyRelevant=v; }),
            Choice("AMMO","QUICK REFILL","Quick Refill key","QuickRefillKey",ZeoOverlay.QuickRefillBinding.Labels,s => ZeoOverlay.QuickRefillBinding.Index(s.QuickRefillKey),(s,v) => s.QuickRefillKey=ZeoOverlay.QuickRefillBinding.Keys[v]),
            Choice("AMMO","QUICK REFILL","Quick Refill modifier","QuickRefillModifier",ZeoOverlay.QuickRefillBinding.Modifiers,s => s.QuickRefillModifier,(s,v) => s.QuickRefillModifier=v),
            Number("AMMO","WANT / HAVE TARGETS","40mm PDC WANT","WantPdc40",0,1000000,100,0,s => s.WantPdc40, (s,v) => s.WantPdc40=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","40mm Improvised PDC WANT","WantPdc40Improvised",0,1000000,100,0,s => s.WantPdc40Improvised, (s,v) => s.WantPdc40Improvised=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","50mm PDC WANT","WantPdc50",0,1000000,100,0,s => s.WantPdc50, (s,v) => s.WantPdc50=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","80mm Sabot WANT","WantSabot80",0,1000000,100,0,s => s.WantSabot80, (s,v) => s.WantSabot80=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","80mm Improvised Sabot WANT","WantSabot80Improvised",0,1000000,100,0,s => s.WantSabot80Improvised, (s,v) => s.WantSabot80Improvised=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","100mm Sabot WANT","WantSabot100",0,1000000,100,0,s => s.WantSabot100, (s,v) => s.WantSabot100=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","160mm Torpedo WANT","WantTorp160",0,100000,5,0,s => s.WantTorp160, (s,v) => s.WantTorp160=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","190mm Torpedo WANT","WantTorp190",0,100000,5,0,s => s.WantTorp190, (s,v) => s.WantTorp190=(int)v),
            Number("AMMO","WANT / HAVE TARGETS","220mm Torpedo WANT","WantTorp220",0,100000,5,0,s => s.WantTorp220, (s,v) => s.WantTorp220=(int)v),
            Bool("AMMO","AMMO TYPE VISIBILITY","40mm PDC","ShowAmmoPdc40",s => s.ShowAmmoPdc40, (s,v) => { s.ShowAmmoPdc40=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","40mm Improvised PDC","ShowAmmoPdc40Improvised",s => s.ShowAmmoPdc40Improvised, (s,v) => { s.ShowAmmoPdc40Improvised=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","50mm PDC","ShowAmmoPdc50",s => s.ShowAmmoPdc50, (s,v) => { s.ShowAmmoPdc50=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","80mm Sabot","ShowAmmoSabot80",s => s.ShowAmmoSabot80, (s,v) => { s.ShowAmmoSabot80=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","80mm Sabot Improvised","ShowAmmoSabot80Improvised",s => s.ShowAmmoSabot80Improvised, (s,v) => { s.ShowAmmoSabot80Improvised=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","100mm Sabot","ShowAmmoSabot100",s => s.ShowAmmoSabot100, (s,v) => { s.ShowAmmoSabot100=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","160mm Torpedo","ShowAmmoTorp160",s => s.ShowAmmoTorp160, (s,v) => { s.ShowAmmoTorp160=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","190mm Torpedo","ShowAmmoTorp190",s => s.ShowAmmoTorp190, (s,v) => { s.ShowAmmoTorp190=v; }),
            Bool("AMMO","AMMO TYPE VISIBILITY","220mm Torpedo","ShowAmmoTorp220",s => s.ShowAmmoTorp220, (s,v) => { s.ShowAmmoTorp220=v; }),
            Bool("ROSTER","FLEET ROSTER","SHOW FLEET ROSTER","ShowRosterPanel",s => s.ShowRosterPanel, (s,v) => { s.ShowRosterPanel=v; }),
            Number("ROSTER","FLEET ROSTER","Roster rows","RosterRows",1,24,1,0,s => s.RosterRows, (s,v) => s.RosterRows=(int)v),
            Bool("ROSTER","FLEET ROSTER","Show allies in other sectors","ShowCrossSectorRoster",s => s.ShowCrossSectorRoster, (s,v) => { s.ShowCrossSectorRoster=v; }),
            Bool("ROSTER","FLEET ROSTER","Unlimited-distance same-sector markers","RemoteFriendlyNoRangeLimit",s => s.RemoteFriendlyNoRangeLimit, (s,v) => { s.RemoteFriendlyNoRangeLimit=v; }),
            Bool("DISTRESS","DISTRESS NETWORK","Enable distress hotkey","DistressEnabled",s => s.DistressEnabled, (s,v) => { s.DistressEnabled=v; }),
            Choice("DISTRESS","DISTRESS NETWORK","DISTRESS KEY","DistressKey",new[] {"F5","F6","F7","F8","F9","F10","F11","F12"},s => s.DistressKey, (s,v) => s.DistressKey=v),
            Choice("DISTRESS","DISTRESS NETWORK","DISTRESS TYPE","DistressType",new[] {"GENERAL SOS","UNDER ATTACK","DISABLED","RECOVERY","NEED FUEL"},s => s.DistressType, (s,v) => s.DistressType=v),
            Choice("DISTRESS","DISTRESS NETWORK","VISIBILITY","DistressVisibility",new[] {"FACTION ONLY","ALLIANCE"},s => s.DistressVisibility, (s,v) => s.DistressVisibility=v),
            Number("DISTRESS","DISTRESS NETWORK","Hold to send seconds","DistressHoldSeconds",0.50,3.00,0.10,2,s => s.DistressHoldSeconds, (s,v) => s.DistressHoldSeconds=v),
            Number("DISTRESS","DISTRESS NETWORK","Distress TTL minutes","DistressTtlMinutes",1,60,1,0,s => s.DistressTtlMinutes, (s,v) => s.DistressTtlMinutes=(int)v),
            Bool("DISTRESS","HUD BEHAVIOR","Show distress alert banner","ShowDistressBanner",s => s.ShowDistressBanner, (s,v) => { s.ShowDistressBanner=v; }),
            Bool("DISTRESS","HUD BEHAVIOR","Show distress world pings","ShowDistressWorldMarkers",s => s.ShowDistressWorldMarkers, (s,v) => { s.ShowDistressWorldMarkers=v; }),
            Bool("DISTRESS","HUD BEHAVIOR","Show cross-sector distress alerts","ShowCrossSectorDistress",s => s.ShowCrossSectorDistress, (s,v) => { s.ShowCrossSectorDistress=v; }),
            Bool("DISTRESS","HUD BEHAVIOR","Project cross-sector distress GPS markers","ProjectCrossSectorDistress",s => s.ProjectCrossSectorDistress, (s,v) => { s.ProjectCrossSectorDistress=v; }),
            Color("DISTRESS","HUD BEHAVIOR","Distress color","DistressColor",s => s.DistressColor, (s,v) => s.DistressColor=v),
        };
        internal static readonly NativeOption Profile = Choice("GLOBAL", "PROFILE", "PROFILE", "Profile",
            new[] { "MINIMAL", "ESSENTIAL", "THREAT PRIORITY", "FULL TACTICAL", "CUSTOM" },
            s => s.Profile, (s,v) => s.ApplyProfile(v));
        internal static readonly NativeOption MenuKey = Choice("GLOBAL", "MENU KEY", "MENU KEY", "MenuKey",
            new[] { "HOME", "INSERT", "PAGE UP", "PAGE DOWN", "END" }, s => s.MenuKey, (s,v) => s.MenuKey=v);
    }
}
